# Generated by Django 5.0.6 on 2024-10-28 14:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tautin_app', '0002_delete_post_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_link', models.URLField(max_length=300)),
                ('short_url_link_address', models.CharField(max_length=255, unique=True)),
                ('short_url_link', models.URLField(blank=True, max_length=300, unique=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2024, 10, 28, 14, 9, 26, 642167, tzinfo=datetime.timezone.utc))),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
