# Generated by Django 5.0.6 on 2024-10-29 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tautin_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 8, 52, 22, 522291, tzinfo=datetime.timezone.utc)),
        ),
    ]
