# Generated by Django 5.0.6 on 2024-11-04 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tautin_app', '0013_alter_link_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 12, 2, 31, 887442, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_url_link_address',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
