# Generated by Django 5.0.6 on 2024-11-04 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tautin_app', '0014_alter_link_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 12, 29, 14, 959476, tzinfo=datetime.timezone.utc)),
        ),
    ]
