# Generated by Django 5.0.6 on 2024-11-06 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tautin_app', '0015_alter_link_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 12, 52, 12, 728651, tzinfo=datetime.timezone.utc)),
        ),
    ]
